### ISSUE TITLE
Question: How is the authState set in AuthService before TaskService needs it?

### ISSUE THREAD

**Issue by JamesBedont** [r-park/todo-angular-firebase#110]
I hope posting questions here is an Ok thing to do. I am trying to learn and using this as an example. :)

Let's say a user refreshes the /tasks route. How is it ensured that the authState in the AuthService is set before the TaskService's constructor tries to use the authState.id when building the database path string?

I am building a similar app and when I refresh the constructor for my TaskService runs, tries to build a database path with the authService.id which at the time is null. Then some time passes and the firebaseAuth subscribe function in the AuthService fires and updates the authState. I would like to make sure that TaskServies doesn' try and build the database path string before the authState is set in the AuthService. I can't figure out how this app is accomplishing this; can anyone help?

I may not have explained this well so if more detail or clarification is needed I'll be happy to try again.

**Comment by mikkeld** [comment]
I have the same question. Please let me know if you find out

**Comment by sbolel** [comment]
The auth guards take care of this. In this case, the [unauth-guard](https://github.com/r-park/todo-angular2-firebase/blob/master/src/auth/guards/unauth-guard.ts).

**Comment by mikkeld** [comment]
Thanks for that. Hopefully you're able to help here.  I copied your implementation of the AuthGuard to my project and have a service similar to your task service that performs the following operation:

```
@Injectable()
export class EmailService {

  private emails: FirebaseListObservable<Email[]>;
  private emailUserPath: string;

  constructor(private af: AngularFire, private authService: AuthService) {
    this.emailUserPath = `/emails/${authService.id}`;
    console.log(this.emailUserPath)
  }

```
The console.log(this.emailUserPath) yields /emails/ only as the ${authService.id} is not yet set

with the following routing module:

```
import { NgModule }             from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { InboxComponent }      from './inbox/inbox.component';
import { ComposeComponent }      from './compose/compose.component';
import { EmailDetailComponent }      from './email-detail/email-detail.component';
import { UserSearchComponent }      from './user-search/user-search.component';
import {AuthGuard} from "./auth/auth-guard";

const routes: Routes = [
  { path: '', redirectTo: '/inbox', pathMatch: 'full', canActivate: [AuthGuard] },
  { path: 'inbox',  component: InboxComponent, canActivate: [AuthGuard] },
  { path: 'compose',  component: ComposeComponent },
  { path: 'search',  component: UserSearchComponent },
  { path: 'email/:id',  component: EmailDetailComponent }
];
@NgModule({
  imports: [ RouterModule.forRoot(routes) ],
  providers: [AuthGuard],
  exports: [ RouterModule ]
})
export class AppRoutingModule {}
```

**Comment by andresespinosapc** [comment]
Isn't it a bad practice? What happens if the user signs out and then signs in with a different account? If I'm right, the TaskService constructor is called once in the app workflow, so the auth.id that was set won't change.

**Comment by r-park** [comment]
Hi @andresespinosapc — to keep the example simple the app reloads the page when the user signs out. In a more complete app the auth id could be retrieved from a store and cleared when the user signs out.

**Comment by andresespinosapc** [comment]
Ok, thanks. Do you know if it's better to do what you say or just subscribe to auth$ when I want to get the user id?

**Comment by r-park** [comment]
Subscribing to auth$ can certainly work.

**Comment by 5im0n** [comment]
What do you think of using the APP_INITIALIZER provider ?
Angular won't load your application before it resolve the promise you define.

```
    {
      provide: APP_INITIALIZER,
      useFactory: (appService: AppService) => ()=>appService.init(),
      multi: true
    }
```
